global:
  scrape_interval: 5s
  external_labels:
    monitor: railway-prom

scrape_configs:
  # Auto-monitoramento do próprio Prometheus
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  # ─────────────────────────────────────────────────────
  # API CloudGames – mesmo projeto Railway
  # ─────────────────────────────────────────────────────
  - job_name: api
    metrics_path: /metrics
    scrape_interval: 5s
    scheme: https
    static_configs:
      - targets: ['fiap-apptechchallenge-production.up.railway.app']